include "exception.h";

void foo(uint-t v);

int-t main()
{
  foo(0);
  foo(k-throw);
  foo(k-throw|k-handle);

  return 0;
}
